coffee_shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('menu/', include('products.urls', namespace='products')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('pages.urls', namespace='pages'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/urls.py
from django.urls import path

from info.views import AboutTemplateView, TestimonialCreateView

app_name = 'info'

urlpatterns = [
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('testimonials/', TestimonialCreateView.as_view(),
         name='testimonials'),
]

pages/urls.py
from django.urls import path

from pages.views import (ContactCreateView, ReservationCreateView,
                         ServiceTemplateView, HomeTemplateView)

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('reservation/', ReservationCreateView.as_view(),
         name='reservation'),
    path('service/', ServiceTemplateView.as_view(), name='service'),
    path('', HomeTemplateView.as_view(), name='home'),
]

products/urls.py
from django.urls import path

from products.views import (load_more_hot_data, load_more_cold_data,
                            MenuListView)

app_name = 'products'

urlpatterns = [
    path('load1/', load_more_hot_data, name='load1'),
    path('load2/', load_more_cold_data, name='load2'),
    path('', MenuListView.as_view(), name='menu'),
]

templates/layouts/footer.html
{% load i18n %}

<div class="container-fluid footer text-white mt-5 pt-5 px-0 position-relative overlay-top">
    <div class="row mx-0 pt-5 px-sm-3 px-lg-5 mt-4">
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">{% trans 'Get In Touch' %}</h4>
            <p>
                <i class="fa fa-map-marker-alt mr-2"></i>{% trans 'Street, Tashkent, Uzbekistan' %}
            </p>
            <p>
                <i class="fa fa-phone-alt mr-2"></i>+998 (71) 123-45-67
            </p>
            <p class="m-0">
                <i class="fa fa-envelope mr-2"></i>info@example.com
            </p>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="text-white text-uppercase mb-4"
                style="letter-spacing: 3px;">{% trans 'Follow Us' %}</h4>
            <p>{% blocktrans %}Do not miss the opportunity to get news about our products and services.{% endblocktrans %}</p>
            <div class="d-flex justify-content-start">
                <a class="btn btn-lg btn-outline-light btn-lg-square mr-2"
                   href="#"><i class="fab fa-telegram"></i></a>
                <a class="btn btn-lg btn-outline-light btn-lg-square mr-2"
                   href="#"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-lg btn-outline-light btn-lg-square mr-2"
                   href="#"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-lg btn-outline-light btn-lg-square" href="#"><i
                        class="fab fa-instagram"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="text-white text-uppercase mb-4"
                style="letter-spacing: 3px;">{% trans 'Working Hours' %}</h4>
            <div>
                <h6 class="text-white text-uppercase">{% blocktrans %}Monday - Friday{% endblocktrans %}</h6>
                <p>09:00 - 20:00</p>
                <h6 class="text-white text-uppercase">{% blocktrans %}Saturday - Sunday{% endblocktrans %}</h6>
                <p>10:00 - 20:00</p>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">{% trans 'Navigation' %}</h4>
            <p>
                <a class="text-white" href="{% url 'info:testimonials' %}">{% trans 'Comments' %}</a>
            </p>
            <p>
                <a class="text-white" href="{% url 'pages:contact' %}">{% trans 'Contacts' %}</a>
            </p>
            <p>
                <a class="text-white" href="{% url 'info:about' %}">{% trans 'About Us' %}</a>
            </p>
        </div>
    </div>
    <div class="container-fluid text-center text-white border-top mt-4 py-4 px-sm-3 px-md-5"
         style="border-color: rgba(256, 256, 256, .1) !important;">
        <p class="m-0 text-white">Cafe | 2023 - <script>document.write(new Date().getFullYear());</script></p>
    </div>
</div>

templates/layouts/header.html
{% load my_tags %}
{% load i18n %}

{% block extra_css %}
    <style>
        @media (max-width: 991.98px) {
            .dm {
                max-width: 4.5rem;
            }
        }
    </style>
{% endblock %}

<div class="container-fluid p-0 nav-bar">
    <nav class="navbar navbar-expand-lg bg-none navbar-dark py-3">
        <a href="{% url 'pages:home' %}" class="navbar-brand px-lg-4 m-0">
            <h1 class="m-0 display-4 text-uppercase text-white">CAFE</h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse"
                data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between"
             id="navbarCollapse">
            <div class="navbar-nav ml-auto p-4">
                <a href="{% url 'pages:home' %}"
                   class="nav-item nav-link {% if request.path == '/en/' or request.path == '/ru/' %}active{% endif %}">{% trans 'Home' %}</a>
                <a href="{% url 'info:about' %}"
                   class="nav-item nav-link {% if request.path == '/en/info/about/' or request.path == '/ru/info/about/' %}active{% endif %}">{% trans 'About Us' %}</a>
                <a href="{% url 'pages:service' %}"
                   class="nav-item nav-link {% if request.path == '/en/service/' or request.path == '/ru/service/' %}active{% endif %}">{% trans 'Service' %}</a>
                <a href="{% url 'products:menu' %}"
                   class="nav-item nav-link {% if request.path == '/en/menu/' or request.path == '/ru/menu/' %}active{% endif %}">{% trans 'Menu' %}</a>
                <a href="{% url 'pages:reservation' %}"
                   class="nav-item nav-link {% if request.path == '/en/reservation/' or request.path == '/ru/reservation/' %}active{% endif %}">{% trans 'Reservation' %}</a>
                <a href="{% url 'pages:contact' %}"
                   class="nav-item nav-link {% if request.path == '/en/contact/' or request.path == '/ru/contact/' %}active{% endif %}">{% trans 'Contacts' %}</a>
                <div class="dropdown">
                    {% get_current_language as lang %}
                    {% get_available_languages as langs %}
                    <a href="#" class="nav-link dropdown-toggle"
                       role="button" id="dropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"
                       style="outline: none;">{{ lang|upper }}</a>
                    <div class="dropdown-menu dm mt-0"
                         style="min-width: 0.5rem;"
                         aria-labelledby="dropdownMenuLink">
                        {% for l in langs %}
                            {% if l.0 != lang %}
                                <a href="{% get_lang_url request l.0 %}"
                                   class="dropdown-item">{{ l.0|upper }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>