coffee_shop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('menu/', include('products.urls', namespace='products')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('pages.urls', namespace='pages'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/urls.py
from django.urls import path

from info.views import AboutTemplateView, TestimonialCreateView

app_name = 'info'

urlpatterns = [
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('testimonials/', TestimonialCreateView.as_view(),
         name='testimonials'),
]

pages/urls.py
from django.urls import path

from pages.views import (ContactCreateView, ReservationCreateView,
                         ServiceTemplateView, HomeTemplateView)

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('reservation/', ReservationCreateView.as_view(),
         name='reservation'),
    path('service/', ServiceTemplateView.as_view(), name='service'),
    path('', HomeTemplateView.as_view(), name='home'),
]

products/urls.py
from django.urls import path

from products.views import (load_more_hot_data, load_more_cold_data,
                            MenuListView)

app_name = 'products'

urlpatterns = [
    path('load1/', load_more_hot_data, name='load1'),
    path('load2/', load_more_cold_data, name='load2'),
    path('', MenuListView.as_view(), name='menu'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "About Us" %}{% endblock %}

{% block content %}
    <div class="container-fluid page-header mb-5 position-relative overlay-bottom">
        <div class="d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5" style="min-height: 400px">
            <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">{% trans 'About Us' %}</h1>
            <div class="d-inline-flex mb-lg-5">
                <p class="m-0 text-white"><a class="text-white" href="{% url 'pages:home' %}">{% trans 'Home' %}</a></p>
                <p class="m-0 text-white px-2">/</p>
                <p class="m-0 text-white">{% trans 'About Us' %}</p>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        {% for about in info %}
            <div class="container">
                <div class="section-title">
                    <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">{{ about.title }}</h4>
                    <h1 class="display-4">{{ about.sub_title }}</h1>
                </div>
                <div class="row">
                    <div class="col-lg-4 py-0 py-lg-5">
                        <h1 class="mb-3">{{ about.left_title }}</h1>
                        <p>{{ about.left_description }}</p>
                    </div>
                    <div class="col-lg-4 py-5 py-lg-0"
                         style="min-height: 500px;">
                        <div class="position-relative h-100">
                            <img class="position-absolute w-100 h-100" src="{{ about.image.url }}" style="object-fit: cover;" alt="">
                        </div>
                    </div>
                    <div class="col-lg-4 py-0 py-lg-5">
                        <h1 class="mb-3">{{ about.right_title }}</h1>
                        <p>{{ about.right_description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
    <!-- Carousel Start -->
    <div class="container-fluid p-0 mb-5">
        <div id="blog-carousel" class="carousel slide overlay-bottom"
             data-ride="carousel">
            <div class="carousel-inner">
                {% for banner in banners %}
                    <div class="carousel-item {% if forloop.first %}active{% else %}{% endif %}">
                        <img class="w-100" src="{{ banner.image.url }}"
                             alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <h2 class="text-primary font-weight-medium m-0">{{ banner.upper_title }}</h2>
                            <h1 class="display-1 text-white m-0">{{ banner.middle_title }}</h1>
                            <h2 class="text-white m-0">{{ banner.lower_title }}</h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#blog-carousel"
               data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#blog-carousel"
               data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    <!-- Carousel End -->


    <!-- About Start -->
    <div class="container-fluid py-5">
        {% for about in info %}
            <div class="container">
                <div class="section-title">
                    <h4 class="text-primary text-uppercase"
                        style="letter-spacing: 5px;">{{ about.title }}</h4>
                    <h1 class="display-4">{{ about.sub_title }}</h1>
                </div>
                <div class="row">
                    <div class="col-lg-4 py-0 py-lg-5">
                        <h1 class="mb-3">{{ about.left_title }}</h1>
                        <p>{{ about.left_description|truncatechars:555 }}</p>
                    </div>
                    <div class="col-lg-4 py-5 py-lg-0"
                         style="min-height: 500px;">
                        <div class="position-relative h-100">
                            <img class="position-absolute w-100 h-100"
                                 src="{{ about.image.url }}"
                                 style="object-fit: cover;" alt="">
                        </div>
                    </div>
                    <div class="col-lg-4 py-0 py-lg-5">
                        <h1 class="mb-3">{{ about.right_title }}</h1>
                        <p>{{ about.right_description|truncatechars:555 }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row text-center mt-4">
            <div class="col-lg-12">
                <a href="{% url 'info:about' %}" class="btn btn-primary font-weight-bold py-2 px-4 mt-2">{% trans 'Learn More' %}</a>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Service Start -->
    <div class="container-fluid pt-5">
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase"
                    style="letter-spacing: 5px;">{% trans 'Our Services' %}</h4>
                <h1 class="display-4">{% trans 'Fresh Beans' %}</h1>
            </div>
            <div class="row">
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            <img class="img-fluid mb-3 mb-sm-0"
                                 src="{% static 'img/service-1.jpg' %}" alt="">
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fa fa-bars service-icon"></i>{% trans 'Variety Of Options' %}</h4>
                            <p class="m-0">{% blocktrans %}Sit lorem ipsum et diam elitr est
                                dolor sed duo. Guberg sea et et lorem dolor sed
                                est sit
                                invidunt, dolore tempor diam ipsum takima erat
                                tempor{% endblocktrans %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            <img class="img-fluid mb-3 mb-sm-0"
                                 src="{% static 'img/service-2.jpg' %}" alt="">
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fa fa-coffee service-icon"></i>{% trans 'Fresh Coffee Beans' %}</h4>
                            <p class="m-0">{% blocktrans %}Sit lorem ipsum et diam elitr est
                                dolor sed duo. Guberg sea et et lorem dolor sed
                                est sit
                                invidunt, dolore tempor diam ipsum takima erat
                                tempor{% endblocktrans %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            <img class="img-fluid mb-3 mb-sm-0"
                                 src="{% static 'img/service-3.jpg' %}" alt="">
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fa fa-award service-icon"></i>{% trans 'Best Quality Coffee' %}</h4>
                            <p class="m-0">{% blocktrans %}Sit lorem ipsum et diam elitr est
                                dolor sed duo. Guberg sea et et lorem dolor sed
                                est sit
                                invidunt, dolore tempor diam ipsum takima erat
                                tempor{% endblocktrans %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            <img class="img-fluid mb-3 mb-sm-0"
                                 src="{% static 'img/service-4.jpg' %}" alt="">
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fa fa-table service-icon"></i>{% trans 'Online Table Booking' %}</h4>
                            <p class="m-0">{% blocktrans %}Sit lorem ipsum et diam elitr est
                                dolor sed duo. Guberg sea et et lorem dolor sed
                                est sit
                                invidunt, dolore tempor diam ipsum takima erat
                                tempor{% endblocktrans %}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->

    <div class="container-fluid pt-5">
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase"
                    style="letter-spacing: 5px;">{% trans 'Menu & Pricing' %}</h4>
                <h1 class="display-4">{% trans 'Competitive Pricing' %}</h1>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mb-5">{% trans 'Hot Coffee' %}</h1>
                    {% for product in hot_products %}
                        <div class="row align-items-center mb-5">
                            <div class="col-4 col-sm-3">
                                <img class="w-100 rounded-circle mb-3 mb-sm-0"
                                     src="{{ product.image.url }}" alt="">
{#                                <h5 class="menu-price">#}
{#                                    ${{ product.price }}#}
{#                                </h5>#}
                            </div>
                            <div class="col-8 col-sm-9">
                                <h4>{{ product.title }}</h4>
                                <h6 class="p-0 m-0">{{ product.price }}</h6>
                                <p class="m-0">{{ product.description }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-lg-6">
                    <h1 class="mb-5">{% trans 'Cold Coffee' %}</h1>
                    {% for product in cold_products %}
                        <div class="row align-items-center mb-5">
                            <div class="col-4 col-sm-3">
                                <img class="w-100 rounded-circle mb-3 mb-sm-0"
                                     src="{{ product.image.url }}" alt="">
                                <h5 class="menu-price">
                                    ${{ product.price }}</h5>
                            </div>
                            <div class="col-8 col-sm-9">
                                <h4>{{ product.title }}</h4>
                                <p class="m-0">{{ product.description }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="text-center">
                <a href="{% url 'products:menu' %}#menu_anchor" class="btn btn-primary font-weight-bold py-2 px-4 mb-5">{% trans 'Learn More' %}</a>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase"
                    style="letter-spacing: 5px;">{% trans 'Testimonial' %}</h4>
                <h1 class="display-4">{% trans 'Our Clients Say' %}</h1>
            </div>
            <div class="owl-carousel testimonial-carousel">
                {% for client in clients %}
                    <div class="testimonial-item">
                        <div class="d-flex align-items-center mb-3">
                            <img class="img-fluid" src="{{ client.image.url }}"
                                 alt="">
                            <div class="ml-3">
                                <h4>{{ client.name }}</h4>
                                <i>{{ client.profession }}</i>
                            </div>
                        </div>
                        <p class="m-0">{{ client.description }}</p>
                    </div>
                {% endfor %}
            </div>
            <div class="d-flex justify-content-end">
                <a href="{% url 'info:testimonials' %}#testimonial_anchor" class="btn btn-primary font-weight-bold py-2 px-4 mt-3">{% trans 'Leave A Comment' %}</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Menu" %}{% endblock %}

{% block content %}
    <div class="container-fluid page-header mb-5 position-relative overlay-bottom">
        <div class="d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5"
             style="min-height: 400px">
            <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">{% trans 'Menu' %}</h1>
            <div class="d-inline-flex mb-lg-5">
                <p class="m-0 text-white"><a class="text-white" href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                </p>
                <p class="m-0 text-white px-2">/</p>
                <p class="m-0 text-white">{% trans 'Menu' %}</p>
            </div>
        </div>
    </div>

    <div class="container-fluid pt-5">
        <div id="menu_anchor"></div>
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase"
                    style="letter-spacing: 5px;">{% trans 'Menu & Pricing' %}</h4>
                <h1 class="display-4">{% trans 'Competitive Pricing' %}</h1>
            </div>
            <div class="row mb-0">
                <div class="col-lg-6 mb-0">
                    <h1 class="text-center mb-5">{% trans 'Hot Coffee' %}</h1>
                    {% for product in hot_products %}
                        <div class="row align-items-center product_box1 mb-5">
                            <div class="col-4 col-sm-3">
                                <img class="w-100 rounded-circle mb-3 mb-sm-0"
                                     src="{{ product.image.url }}" alt="">
{#                                <h5 class="menu-price">#}
{#                                    ${{ product.price }}#}
{#                                </h5>#}
                            </div>
                            <div class="col-8 col-sm-9">
                                <h4>{{ product.title }}</h4>
                                <h6 class="p-0 m-0">{{ product.price }}</h6>
                                <p class="m-0">{{ product.description }}</p>
                            </div>
                        </div>
                    {% endfor %}
                    <div id="products1"></div>
                    <div class="text-center">
                        <button id="load_more_btn1"
                                class="btn btn-primary font-weight-bold py-2 px-4 mb-5"
                                data-total="{{ total_hot_products }}"
                                data-limit="2">
                            {% trans 'Load More' %}
                        </button>
                        <div class="after_button1"></div>
                    </div>
                </div>
                <div class="col-lg-6 mb-0">
                    <h1 class="text-center mb-5">{% trans 'Cold Coffee' %}</h1>
                    {% for product in cold_products %}
                        <div class="row align-items-center product_box2 mb-5">
                            <div class="col-4 col-sm-3">
                                <img class="w-100 rounded-circle mb-3 mb-sm-0"
                                     src="{{ product.image.url }}" alt="">
                                <h5 class="menu-price">
                                    ${{ product.price }}</h5>
                            </div>
                            <div class="col-8 col-sm-9">
                                <h4>{{ product.title }}</h4>
                                <p class="m-0">{{ product.description }}</p>
                            </div>
                        </div>
                    {% endfor %}
                    <div id="products2"></div>
                    <div class="text-center">
                        <button id="load_more_btn2"
                                class="btn btn-primary font-weight-bold py-2 px-4 mb-5"
                                data-total="{{ total_cold_products }}"
                                data-limit="2">
                            {% trans 'Load More' %}
                        </button>
                        <div class="after_button2"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        $(document).ready(function () {
            $("#load_more_btn1").on("click", function () {
                let current_products = $(".product_box1").length;
                let limit = $(this).attr('data-limit');
                let total = $(this).attr('data-total');

                $.ajax({
                    url: "{% url 'products:load1' %}",
                    data: {
                        limit: limit,
                        offset: current_products
                    },
                    dataType: 'json',
                    beforeSend: function () {

                    },
                    success: function (res) {
                        $("#products1").append(res.hot_products);
                        //console.log(res.hot_products);

                        let total_showing = $(".product_box1").length;
                        if (total_showing == total) {
                            $('#load_more_btn1').remove();
                            $(".after_button1").append("<p>No more products!</p>")
                        }
                    },
                });
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#load_more_btn2").on("click", function () {
                let current_products = $(".product_box2").length;
                let limit = $(this).attr('data-limit');
                let total = $(this).attr('data-total');

                $.ajax({
                    url: "{% url 'products:load2' %}",
                    data: {
                        limit: limit,
                        offset: current_products
                    },
                    dataType: 'json',
                    beforeSend: function () {

                    },
                    success: function (res) {
                        $("#products2").append(res.cold_products);
                        //console.log(res.cold_products);

                        let total_showing = $(".product_box2").length;
                        if (total_showing == total) {
                            $('#load_more_btn2').remove();
                            $(".after_button2").append("<p>No more products!</p>")
                        }
                    },
                });
            });
        });
    </script>
{% endblock %}

templates/reservation.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Reservation" %}{% endblock %}

{% block content %}
    <div class="container-fluid page-header mb-5 position-relative overlay-bottom">
        <div class="d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5"
             style="min-height: 400px">
            <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">{% trans 'Reservation' %}</h1>
            <div class="d-inline-flex mb-lg-5">
                <p class="m-0 text-white"><a class="text-white" href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                </p>
                <p class="m-0 text-white px-2">/</p>
                <p class="m-0 text-white">{% trans 'Reservation' %}</p>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div class="container">
            <div class="reservation position-relative overlay-top overlay-bottom">
                <div class="row align-items-center">
                    <div class="col-lg-6 my-5 my-lg-0">
                        {% for info in reservation_info %}
                            <div class="p-5">
                                <div class="mb-4">
                                    <h1 class="display-3 text-primary">{{ info.discount_title }}</h1>
                                    <h1 class="text-white">{{ info.sub_title }}</h1>
                                </div>
                                <p class="text-white">{{ info.description }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-lg-6">
                        <div class="text-center p-5"
                             style="background: rgba(51, 33, 29, .8);">
                            <h1 class="text-white mb-4 mt-5">{% trans 'Book Your Table' %}</h1>
                            <form class="mb-5" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input name="name" type="text"
                                           class="form-control bg-transparent border-primary p-4"
                                           placeholder="{% trans 'Name' %}"
                                           required="required"/>
                                </div>
                                <div class="form-group">
                                    <input name="email" type="email"
                                           class="form-control bg-transparent border-primary p-4"
                                           placeholder="{% trans 'Email' %}"
                                           required="required"/>
                                </div>
                                <div class="form-group">
                                    <input name="date" type="date"
                                           class="form-control bg-transparent border-primary"
                                           placeholder="{% now "d/m/Y" %}"
                                           required="required"
                                           style="color: #6c757d; padding: 0.7rem 0 2.3rem 1.45rem"/>
                                </div>
                                <div class="form-group">
                                    <input name="time" type="time"
                                           class="form-control bg-transparent border-primary"
                                           placeholder="{% now "H:i" %}"
                                           required="required"
                                           style="color: #6c757d; padding: 0.7rem 0 2.3rem 1.35rem"/>
                                </div>
                                <div class="form-group">
                                    <input name="number_of_people"
                                           min="1"
                                           type="number"
                                           class="form-control bg-transparent border-primary p-4"
                                           placeholder="{% trans 'Number of People' %}"
                                           required="required"/>
                                </div>
                                <div>
                                    <button type="submit"
                                            class="btn btn-primary btn-block font-weight-bold py-3">
                                        {% trans 'Book Now' %}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        {% if messages %}
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}

templates/testimonial.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Testimonial" %}{% endblock %}

{% block content %}
    <div class="container-fluid page-header mb-5 position-relative overlay-bottom">
        <div class="d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5"
             style="min-height: 400px">
            <h1 class="display-4 mb-3 mt-0 mt-lg-5 text-white text-uppercase">
                {% trans 'Testimonials' %}</h1>
            <div class="d-inline-flex mb-lg-5">
                <p class="m-0 text-white"><a class="text-white"
                                             href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                </p>
                <p class="m-0 text-white px-2">/</p>
                <p class="m-0 text-white">{% trans 'Testimonials' %}</p>
            </div>
        </div>
    </div>

    <div class="container-fluid py-5">
        <div id="testimonial_anchor"></div>
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase"
                    style="letter-spacing: 5px;">{% trans 'Testimonial' %}</h4>
                <h1 class="display-4">{% trans 'Our Clients Say' %}</h1>
            </div>
            <div class="owl-carousel testimonial-carousel">
                {% for client in clients %}
                    <div class="testimonial-item">
                        <div class="d-flex align-items-center mb-3">
                            <img class="img-fluid" src="{{ client.image.url }}"
                                 alt="">
                            <div class="ml-3">
                                <h4>{{ client.name }}</h4>
                                <i>{{ client.profession }}</i>
                            </div>
                        </div>
                        <p class="m-0">{{ client.description }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container-fluid my-5">
        <div class="container">
            <form method="POST" action="{% url 'info:testimonials' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12 text-center mb-3">
                        <h1 class="display-5">{% trans 'Post a comment' %}</h1>
                    </div>
                    <div class="col-lg-6">
                        <div class="contact-form">
                            <div class="control-group">
                                <input name="image" type="file" class="form-control-file" required>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input name="name" type="text" class="form-control bg-transparent p-4" placeholder="{% trans 'Your Name' %}" required>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input name="profession" type="text" class="form-control bg-transparent p-4" placeholder="{% trans 'Your Profession' %}" required>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="contact-form">
                            <div class="control-group">
                                <textarea name="description" class="form-control bg-transparent py-2 px-3" rows="6" placeholder="{% trans 'Comment' %}" required></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 text-right">
                        <button type="submit" class="btn btn-primary font-weight-bold py-3 px-5">{% trans 'Submit' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}